[+]add a task query method
adamwojs/php-activiti-api pull request #3
Opened 2018-03-13 06:13 UTC by dark-wind

query/task can query with candidateUser

2018-03-14 19:58 UTC, adamwojs requested changes
Thank you for this contribution. Looks good, besides nitpicks related to code style :-)

2018-03-14 19:58 UTC, adamwojs commented on src/Client/Service/TaskService.php
> +     * @param TaskQuery|null $query
`@param` is not needed if `{@inheritdoc}` is present.

2018-03-14 19:58 UTC, adamwojs commented on src/Client/Service/TaskServiceInterface.php
> +     * @return mixed
Should be `TaskList` instead of `mixed`

2018-03-14 19:58 UTC, adamwojs commented on src/Client/Service/TaskServiceInterface.php
> +    public function queryTask(TaskQuery $query = null);
Method name should be in plural form: `queryTasks`

2018-03-15 03:34 UTC, dark-wind commented
Thank you for taking the time to check carefully. I have modified the code style. I apologize for my carelessness.

2018-03-15 19:07 UTC, adamwojs approved these changes

2018-03-15 19:08 UTC, merged

2018-03-15 19:09 UTC, adamwojs commented
> Thank you for taking the time to check carefully. I have modified the code style. I apologize for my carelessness.

No problem @dark-wind :wink: